apiVersion: v1
kind: LimitRange
metadata:
  name: resilience-lab-limits
  namespace: resilience-lab
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 10m
        memory: 16Mi
